/**
 * Design Token Module — type-safe CSS custom property references.
 *
 * Rule: Never write 'var(--theme-*)' magic strings in component files.
 *       Import from this module for all inline-style `style={{}}` usage.
 *
 * For Tailwind class strings (className=) use the Tailwind utilities
 * generated by @theme inline in tokens.css (e.g. `bg-status-success`).
 *
 * SSOT: web/app/tokens.css (Layer 2 semantic tokens)
 */

export const tokens = {
  // ── Backgrounds ─────────────────────────────────────────────────────────
  bg: {
    page:     'var(--theme-bg-page)',
    card:     'var(--theme-bg-card)',
    elevated: 'var(--theme-bg-elevated)',
    hover:    'var(--theme-bg-hover)',
  },

  // ── Text ────────────────────────────────────────────────────────────────
  text: {
    primary:   'var(--theme-text-primary)',
    secondary: 'var(--theme-text-secondary)',
    bright:    'var(--theme-text-bright)',
    dim:       'var(--theme-text-dim)',
    faint:     'var(--theme-text-faint)',
  },

  // ── Border ──────────────────────────────────────────────────────────────
  border: {
    base:    'var(--theme-border)',
    subtle:  'var(--theme-border-subtle)',
    default: 'var(--theme-border-default)',
  },

  // ── Brand ───────────────────────────────────────────────────────────────
  brand: {
    primary:    'var(--theme-primary)',
    foreground: 'var(--theme-primary-foreground)',
    ring:       'var(--theme-ring)',
    focusRing:  'var(--theme-focus-ring)',
  },

  // ── Status (background / icon colour) ───────────────────────────────────
  status: {
    success:   'var(--theme-status-success)',
    error:     'var(--theme-status-error)',
    warning:   'var(--theme-status-warning)',
    info:      'var(--theme-status-info)',
    cancelled: 'var(--theme-status-cancelled)',
  },

  // ── Status foreground (text colour) ─────────────────────────────────────
  statusFg: {
    success: 'var(--theme-status-success-fg)',
    error:   'var(--theme-status-error-fg)',
    warning: 'var(--theme-status-warning-fg)',
    info:    'var(--theme-status-info-fg)',
  },

  // ── Accents ─────────────────────────────────────────────────────────────
  accent: {
    gpu:   'var(--theme-accent-gpu)',
    power: 'var(--theme-accent-power)',
    brand: 'var(--theme-accent-brand)',
  },

  // ── Charts ──────────────────────────────────────────────────────────────
  chart: {
    c1: 'var(--theme-chart-1)',
    c2: 'var(--theme-chart-2)',
    c3: 'var(--theme-chart-3)',
    c4: 'var(--theme-chart-4)',
    c5: 'var(--theme-chart-5)',
  },

  // ── Logo ─────────────────────────────────────────────────────────────────
  logo: {
    start: 'var(--theme-logo-start)',
    end:   'var(--theme-logo-end)',
    inner: 'var(--theme-logo-inner)',
  },
} as const

/** Union of all CSS variable strings defined in this module. */
export type ThemeToken = (typeof tokens)[keyof typeof tokens][keyof (typeof tokens)[keyof typeof tokens]]
