/**
 * API response DTOs — hand-written to match the backend's JSON shape.
 *
 * Domain types (JobStatus, JobSource, etc.) are re-exported from
 * `./generated` (auto-generated by ts-rs from Rust enums).
 *
 * These response DTOs intentionally differ from ts-rs types:
 * the API omits internal fields (key_hash, password_hash, deleted_at, …)
 * and serializes UUIDs/dates as strings.
 */

import type { JobStatus, JobSource, ProviderType, LlmProviderStatus, GpuServer } from './generated'

/** Connection verification state for server/provider registration modals. */
export type VerifyState = 'idle' | 'checking' | 'ok' | 'error'

/**
 * HTTP error thrown by custom fetch helpers (verifyServer, verifyProvider).
 * Carries the HTTP status code so callers can distinguish 409 Conflict from 5xx errors.
 */
export class ApiHttpError extends Error {
  constructor(message: string, public readonly status: number) {
    super(message)
    this.name = 'ApiHttpError'
  }
}

/**
 * API key as returned by the dashboard API.
 * Omits internal fields (key_hash, deleted_at, key_type) not in API responses.
 */
export interface ApiKey {
  id: string
  key_prefix: string
  name: string
  tenant_id: string
  is_active: boolean
  rate_limit_rpm: number
  rate_limit_tpm: number
  created_at: string
  expires_at: string | null
  /** Billing tier: `"free"` or `"paid"` */
  tier: 'free' | 'paid'
  /** MCP capability points (0–10, default 3). Controls how many MCP tools this key may use per request. */
  mcp_cap_points: number
  /** Username of the creator (super admin view) */
  created_by?: string
}

// ── Re-exported generated enums (SSOT: Rust domain → ts-rs → here) ──────────
export type { JobStatus, JobSource, ProviderType, LlmProviderStatus } from './generated'
/** Re-export GpuServer as-is — API response shape matches domain entity 1:1. */
export type { GpuServer } from './generated'

/** Fields shared by both the list-level Job and the detail-level JobDetail. */
export interface JobBase {
  id: string
  model_name: string
  provider_type: string
  status: JobStatus
  source: JobSource
  created_at: string
  completed_at: string | null
  latency_ms: number | null
  ttft_ms: number | null
  prompt_tokens: number | null
  completion_tokens: number | null
  cached_tokens: number | null
  tps: number | null
  api_key_name: string | null
  /** For test run jobs: the account name of who ran it. */
  account_name: string | null
  /** HTTP path the request arrived via, e.g. "/v1/chat/completions" */
  request_path: string | null
  /** Estimated API cost in USD. 0.00 for Ollama (self-hosted). null = no pricing data. */
  estimated_cost_usd: number | null
}

export interface Job extends JobBase {
  /** True when the model responded with tool calls instead of text. */
  has_tool_calls: boolean
  /** Name of the provider (Ollama server) that processed this job. */
  provider_name: string | null
  /** Conversation this job belongs to (multi-turn), if any. */
  conversation_id: string | null
}

export interface ChatMessage {
  role: 'system' | 'user' | 'assistant' | 'tool'
  content: string | null
  /** For tool-role messages: the tool call id this is a response to. */
  tool_call_id?: string
  /** For tool-role messages: the function name. */
  name?: string
  /** Tool calls emitted by the assistant (role=assistant with function calls). */
  tool_calls?: ToolCall[]
}

export interface ToolCall {
  id?: string
  function?: {
    name: string
    index?: number
    arguments?: Record<string, unknown> | string
  }
}

export interface JobDetail extends JobBase {
  started_at: string | null
  prompt: string
  result_text: string | null
  error: string | null
  /** Tool calls emitted by the model (when responding with function calls instead of text). */
  tool_calls_json: ToolCall[] | null
  /** Number of messages in the conversation context (multi-turn agent loop). */
  message_count: number | null
  /** Full conversation context sent to the model. Null for single-turn or pre-migration jobs. */
  messages_json: ChatMessage[] | null
  /** Name of the provider (Ollama server) that processed this job. */
  provider_name: string | null
  /** S3 keys for stored WebP images. */
  image_keys: string[] | null
  /** Resolved URLs for image thumbnails/full images. */
  image_urls: string[] | null
}

export interface DashboardStats {
  total_keys: number
  /** Active standard (non-test) keys */
  active_keys: number
  total_jobs: number
  jobs_last_24h: number
  jobs_by_status: Record<string, number>
}

export interface QueueDepth {
  api_paid: number
  api: number
  test: number
  total: number
}

export interface UsageAggregate {
  request_count: number
  success_count: number
  cancelled_count: number
  error_count: number
  prompt_tokens: number
  completion_tokens: number
  total_tokens: number
}

export interface HourlyUsage {
  hour: string
  request_count: number
  success_count: number
  cancelled_count: number
  error_count: number
  prompt_tokens: number
  completion_tokens: number
  total_tokens: number
}

export interface PerformanceStats {
  avg_latency_ms: number
  p50_latency_ms: number
  p95_latency_ms: number
  p99_latency_ms: number
  total_requests: number
  success_rate: number
  total_tokens: number
  hourly: HourlyThroughput[]
}

export interface ModelStat {
  model_name: string
  request_count: number
  success_count: number
  success_rate: number
  total_prompt_tokens: number
  total_completion_tokens: number
  avg_latency_ms: number
}

export interface FinishReasonStat {
  reason: string
  count: number
}

export interface AnalyticsStats {
  avg_tps: number
  avg_prompt_tokens: number
  avg_completion_tokens: number
  models: ModelStat[]
  finish_reasons: FinishReasonStat[]
}

export interface HourlyThroughput {
  hour: string
  request_count: number
  success_count: number
  avg_latency_ms: number
  total_tokens: number
}

export interface ProviderBreakdown {
  provider_type: string
  request_count: number
  success_count: number
  error_count: number
  prompt_tokens: number
  completion_tokens: number
  success_rate: number
  estimated_cost_usd: number | null
}

export interface KeyBreakdown {
  key_id: string
  key_name: string
  key_prefix: string
  request_count: number
  success_count: number
  error_count: number
  cancelled_count: number
  prompt_tokens: number
  completion_tokens: number
  success_rate: number
  estimated_cost_usd: number | null
}

export interface ModelBreakdown {
  model_name: string
  provider_type: string
  request_count: number
  call_pct: number
  prompt_tokens: number
  completion_tokens: number
  avg_latency_ms: number
  estimated_cost_usd: number | null
}

export interface UsageBreakdown {
  by_providers: ProviderBreakdown[]
  by_key: KeyBreakdown[]
  by_model: ModelBreakdown[]
  total_cost_usd: number
}

export interface CreateKeyRequest {
  name: string
  tenant_id: string
  rate_limit_rpm?: number
  rate_limit_tpm?: number
  /** Billing tier: `"free"` or `"paid"` (default) */
  tier?: 'free' | 'paid'
}

// GpuServer: re-exported from generated (see above)

export interface RegisterGpuServerRequest {
  name: string
  node_exporter_url?: string
}

export interface UpdateGpuServerRequest {
  name?: string
  node_exporter_url?: string
}

export interface NodeMetrics {
  scrape_ok: boolean
  mem_total_mb: number
  mem_available_mb: number
  /** Logical CPUs (hardware threads) */
  cpu_logical: number
  /** Physical cores — null when node_cpu_info is not available */
  cpu_physical: number | null
  /** Instantaneous CPU usage 0–100 %. null on first scrape (no delta yet) */
  cpu_usage_pct: number | null
  gpus: GpuNodeMetrics[]
}

export interface GpuNodeMetrics {
  card: string
  temp_c: number | null
  temp_junction_c: number | null
  temp_mem_c: number | null
  power_w: number | null
  vram_used_mb: number | null
  vram_total_mb: number | null
  busy_pct: number | null
}

export interface Provider {
  id: string
  name: string
  provider_type: ProviderType
  url: string
  timeout_secs?: number
  is_active: boolean
  total_vram_mb: number
  /** GPU index on the host (0-based). Used to filter node-exporter metrics. */
  gpu_index: number | null
  /** FK → gpu_servers. null for cloud providers. */
  server_id: string | null
  /** true = Google free-tier project; RPM/RPD limits come from gemini_rate_limit_policies. */
  is_free_tier: boolean
  status: LlmProviderStatus
  registered_at: string
  /** Masked API key shown in the UI (e.g. `AIza...x1y2`). Gemini only. */
  api_key_masked: string | null
}

export interface ProviderPage {
  providers: Provider[]
  total: number
  page: number
  limit: number
}

export interface KeyPage {
  keys: ApiKey[]
  total: number
  page: number
  limit: number
}

export interface AccountPage {
  accounts: Account[]
  total: number
  page: number
  limit: number
}

export interface ServerPage {
  servers: GpuServer[]
  total: number
  page: number
  limit: number
}

export interface RegisterProviderRequest {
  name: string
  provider_type: ProviderType
  url?: string
  api_key?: string
  total_vram_mb?: number
  gpu_index?: number
  server_id?: string
  is_free_tier?: boolean
}

export interface UpdateProviderRequest {
  name: string
  url?: string
  api_key?: string
  total_vram_mb?: number
  gpu_index?: number | null
  server_id?: string | null
  is_free_tier?: boolean
  is_active?: boolean
}

export interface GeminiStatusResult {
  id: string
  name: string
  status: LlmProviderStatus
  error: string | null
}

export interface GeminiStatusSyncResponse {
  synced_at: string
  results: GeminiStatusResult[]
}

/** Per-model Gemini rate-limit policy. model_name="*" = global fallback. */
export interface GeminiRateLimitPolicy {
  id: string
  model_name: string
  rpm_limit: number
  rpd_limit: number
  /**
   * When false: skip all free-tier providers and route directly to a paid provider.
   * RPM/RPD counters are also suppressed for paid providers.
   */
  available_on_free_tier: boolean
  updated_at: string
}

export interface UpsertGeminiPolicyRequest {
  rpm_limit: number
  rpd_limit: number
  available_on_free_tier: boolean
}

export interface ServerMetricsPoint {
  ts: string
  mem_total_mb: number
  mem_avail_mb: number
  gpu_temp_c: number | null
  gpu_temp_junction_c: number | null
  gpu_temp_mem_c: number | null
  gpu_power_w: number | null
  /** CPU usage percentage (0–100). Computed from delta of node_cpu_seconds_total counters. */
  cpu_usage_pct: number | null
  /** CPU package temperature in °C. Intel: coretemp Package id 0, AMD: k10temp Tctl/Tdie. */
  cpu_temp_c: number | null
}

export interface ProviderSelectedModel {
  model_name: string
  is_enabled: boolean
  synced_at: string
}

export interface GeminiSyncConfig {
  api_key_masked: string | null
}

export interface GeminiModel {
  model_name: string
  synced_at: string
}

export interface RegisterProviderResponse {
  id: string
  status: string
}

export interface CreateKeyResponse {
  id: string
  key: string
  key_prefix: string
  tenant_id: string
  created_at: string
}

export interface OllamaSyncResult {
  provider_id: string
  name: string
  models: string[]
  error: string | null
}

export interface OllamaSyncJob {
  id: string
  started_at: string
  completed_at: string | null
  status: 'running' | 'completed'
  total_providers: number
  done_providers: number
  results: OllamaSyncResult[]
}

/** Model with count of providers that carry it (from GET /v1/ollama/models). */
export interface OllamaModelWithCount {
  model_name: string
  provider_count: number
  is_vision?: boolean
  /** Maximum context window across providers (0 = not yet profiled). */
  max_ctx?: number
}

/** Provider info returned by GET /v1/ollama/models/:model_name/providers. */
export interface RetryParams {
  prompt: string
  model: string
  provider_type: string
}

export interface OllamaProviderForModel {
  provider_id: string
  name: string
  url: string
  timeout_secs?: number
  status: string
  is_enabled: boolean
}

export interface OllamaModelPage {
  models: OllamaModelWithCount[]
  total: number
  page: number
  limit: number
}

export interface OllamaProviderPage {
  providers: OllamaProviderForModel[]
  total: number
  page: number
  limit: number
}

/**
 * Account as returned by the dashboard API.
 * Omits internal fields (password_hash, deleted_at, created_by)
 * and narrows `role` to the concrete string union.
 */
export interface RoleSummary {
  id: string
  name: string
  permissions: string[]
  menus: string[]
  is_system: boolean
  account_count: number
  created_at: string
}

export interface RoleInfo {
  id: string
  name: string
}

export interface Account {
  id: string
  username: string
  name: string
  email: string | null
  roles: RoleInfo[]
  role_name: string
  permissions: string[]
  menus: string[]
  department: string | null
  position: string | null
  is_active: boolean
  last_login_at: string | null
  created_at: string
}

export interface CreateAccountRequest {
  username: string
  password: string
  name: string
  email?: string
  role_ids?: string[]
  /** Legacy single role_id — fallback when role_ids is empty. */
  role_id?: string
  department?: string
  position?: string
}

export interface CreateAccountResponse {
  id: string
  username: string
  test_api_key: string
  created_at: string
}

export interface LoginRequest {
  username: string
  password: string
}

export interface LoginResponse {
  ok: boolean
  account_id: string
  username: string
  role: string
  permissions: string[]
  menus: string[]
}

export interface SessionRecord {
  id: string
  ip_address: string | null
  created_at: string
  last_used_at: string | null
  expires_at: string
}

export interface LoadedModelInfo {
  model_name: string
  weight_mb: number
  kv_per_request_mb: number
  active_requests: number
  /** Adaptive concurrency limit (AIMD). 0 = unlimited. */
  max_concurrent: number
  llm_concern: string | null
  llm_reason: string | null
}

export interface ProviderVramInfo {
  provider_id: string
  provider_name: string
  total_vram_mb: number
  used_vram_mb: number
  available_vram_mb: number
  thermal_state: 'normal' | 'soft' | 'hard'
  temp_c: number | null
  loaded_models: LoadedModelInfo[]
}

export interface CapacityPageResponse {
  providers: ProviderVramInfo[]
  total: number
  page: number
  limit: number
}

export interface ClusterModelInfo {
  model_name: string
  weight_mb: number
  kv_per_request_mb: number
  total_active: number
  total_limit: number
  provider_count: number
}

export interface SyncSettings {
  analyzer_model: string
  sync_enabled: boolean
  sync_interval_secs: number
  /** AIMD probe: extra (+) or fewer (-) concurrent requests for learning. */
  probe_permits: number
  /** AIMD probe: every N arrivals at the limit, apply probe. 0 = disabled. */
  probe_rate: number
  last_run_at: string | null
  last_run_status: string | null
  available_models: Record<string, string[]>
}

export interface PatchSyncSettings {
  analyzer_model?: string
  sync_enabled?: boolean
  sync_interval_secs?: number
  probe_permits?: number
  probe_rate?: number
}

export interface LabSettings {
  gemini_function_calling: boolean
  max_images_per_request: number
  max_image_b64_bytes: number
  context_compression_enabled: boolean
  compression_model: string | null
  context_budget_ratio: number
  compression_trigger_turns: number
  recent_verbatim_window: number
  compression_timeout_secs: number
  multiturn_min_params: number
  multiturn_min_ctx: number
  multiturn_allowed_models: string[]
  vision_model: string | null
  handoff_enabled: boolean
  handoff_threshold: number
  updated_at: string
}

export interface PatchLabSettings {
  gemini_function_calling?: boolean
  max_images_per_request?: number
  max_image_b64_bytes?: number
  context_compression_enabled?: boolean
  compression_model?: string | null
  context_budget_ratio?: number
  compression_trigger_turns?: number
  recent_verbatim_window?: number
  compression_timeout_secs?: number
  multiturn_min_params?: number
  multiturn_min_ctx?: number
  multiturn_allowed_models?: string[]
  vision_model?: string | null
  handoff_enabled?: boolean
  handoff_threshold?: number
}

export interface MultiturnWarning {
  code: 'model_too_small' | 'context_too_small' | 'model_not_allowed'
  message: string
}

/** Aggregated snapshot from GET /v1/dashboard/overview — replaces individual stats/perf/queue/lab queries. */
export interface DashboardOverview {
  stats: DashboardStats
  performance: PerformanceStats
  queue_depth: QueueDepth
  lab: LabSettings
}

export interface ConversationSummary {
  id: string
  title?: string | null
  model_name: string | null
  source: string
  turn_count: number
  total_prompt_tokens: number
  total_completion_tokens: number
  created_at: string
  updated_at: string
}

export interface ConversationTurn {
  job_id: string
  prompt: string
  result: string | null
  tool_calls?: Array<{ function?: { name?: string; arguments?: string } }> | null
  model_name?: string | null
  created_at: string
}

export interface ConversationDetail extends ConversationSummary {
  turns: ConversationTurn[]
}

export interface TurnInternals {
  job_id: string
  compressed?: {
    summary: string
    original_tokens: number
    compressed_tokens: number
    compression_model: string
    ratio: number
  } | null
  vision_analysis?: {
    analysis: string
    vision_model: string
    image_count: number
    analysis_tokens: number
  } | null
}

export interface AuditEvent {
  event_time: string
  account_id: string
  account_name: string
  action: string
  resource_type: string
  resource_id: string
  resource_name: string
  ip_address: string
  details: string
}

export interface InfraServiceItem {
  name: string
  status: string
  checked_at: number | null
  latency_ms?: number | null
}

export interface PodItem {
  id: string
  status: string
  last_heartbeat_ms?: number | null
}

export interface ServiceHealthResponse {
  infrastructure: InfraServiceItem[]
  api_pods: PodItem[]
  agent_pods: PodItem[]
}

export interface TopicPipelineStats {
  topic: string
  consumer_offset: number
  log_end_offset: number
  lag: number
  tpm_1m: number
  tpm_5m: number
  last_poll_secs: number | null
  is_active: boolean
  last_error: string | null
  consumer_count: number
}

export interface PipelineHealthResponse {
  topics: TopicPipelineStats[]
  available: boolean
}

export interface McpServer {
  id: string
  name: string
  slug: string
  url: string
  timeout_secs?: number
  is_enabled: boolean
  tool_count: number
  online?: boolean
  created_at: string
}

export interface McpServerStat {
  server_slug: string
  server_name: string
  total_calls: number
  success_rate: number
  cache_hit_count: number
  avg_latency_ms: number
}

export interface McpServerAccess {
  server_id: string
  server_name: string
  is_allowed: boolean
  slug?: string
  /** Top-K tool limit for this key/server pair. null = no override (use server default). */
  top_k: number | null
}

export interface McpSettings {
  routing_cache_ttl_secs: number
  tool_schema_refresh_secs: number
  embedding_model: string
  max_tools_per_request: number
  max_routing_cache_entries: number
}

export interface RegisterMcpServerRequest {
  name: string
  slug: string
  url: string
  timeout_secs?: number
}
