pub mod account_handlers;
pub mod audit_handlers;
pub mod audit_helpers;
pub mod auth_handlers;
pub mod constants;
pub mod error;
pub mod cancel_guard;
pub mod model_selection_handlers;
pub mod provider_handlers;
mod provider_validation;
pub mod docs_handlers;
pub mod dashboard_handlers;
mod dashboard_queries;
pub mod gemini_compat_handlers;
pub mod gemini_helpers;
pub mod gemini_model_handlers;
pub mod ollama_compat_handlers;
pub mod gemini_policy_handlers;
pub mod gpu_server_handlers;
pub mod handlers;
pub mod inference_helpers;
pub mod key_handlers;
pub mod metrics_handlers;
pub mod middleware;
pub mod ollama_model_handlers;
pub mod openai_handlers;
pub mod openai_sse_types;
pub mod openai_models_handlers;
pub mod openai_embeddings_handlers;
pub mod openai_completions_handlers;
pub mod openai_media_handlers;
mod query_helpers;
pub mod test_handlers;
pub mod router;
pub mod state;
pub mod usage_handlers;
mod usage_queries;
#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
pub(crate) mod test_support;
