{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "inferq.fullname" . }}-postgres
  labels:
    {{- include "inferq.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgres.storage.storageClassName }}
  storageClassName: {{ .Values.postgres.storage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size | quote }}
{{- end }}
