{{- if .Values.clickhouse.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "inferq.fullname" . }}-clickhouse
  labels:
    {{- include "inferq.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.clickhouse.storage.storageClassName }}
  storageClassName: {{ .Values.clickhouse.storage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.clickhouse.storage.size | quote }}
{{- end }}
